defining a base class for layers


In [ ]:
import numpy as np
from Activation_Functions.Layer import Layer

In [39]:
#linear layer 
class Linear(Layer):
    def __init__ (self, input_dim, output_dim):
        super().__init__()
        self.w = 0.1 * np.random.rand(input_dim, output_dim)
        self.b = np.zeros((1, output_dim))
        self.dw = np.zeros_like(self.w)
        self.db = np.zeros_like(self.b)
    def forward(self, input):
        self.input  = input
        self.output= np.dot(input, self.w) + self.b
        return self.output
    def backward(self, up_gradient: np.ndarray) -> np.ndarray:
        """Backpropagate the gradients through this layer."""
        #dw = dL/dw
        self.dw = np.dot(self.input.T, up_gradient)  
        self.db = np.sum(up_gradient, axis=0, keepdims=True)
        down_grad = np.dot(up_gradient, self.w.T)
        return down_grad
    def step(self, learning_rate: float) -> None:
        """Update the weights and biases using the gradients."""
        self.w -= learning_rate * self.dw
        self.b -= learning_rate * self.db

In [ ]:
# #testing the linearilty
# np.random.seed(0)  
# linear_layer = Linear(3, 2)
# input = np.array([[1.0, 2.0, 3.0]]) 
# output = linear_layer(input)
# print("Input:\n", input)
# print("Weights:\n", linear_layer.w)
# print("Biases:\n", linear_layer.b)
# print("Output:\n", output)

Input:
 [[1. 2. 3.]]
Weights:
 [[0.05488135 0.07151894]
 [0.06027634 0.05448832]
 [0.04236548 0.06458941]]
Biases:
 [[0. 0.]]
Output:
 [[0.30253047 0.37426381]]


In [43]:
import sys 
sys.path.append('../')
from Activation_Functions.Sigmoid import Sigmoid

NameError: name 'Layer' is not defined